### ISSUE TITLE
Position of widget from header to down

### ISSUE THREAD

**Issue by ghost** [FriendsOfFlarum/forum-statistics-widget#16]
Hi how to move the FoF Statistics plugin widget at the mobile interface from the header down.
Any chance via CSS, or how. Thank you.

My plugin version is: 0.6.0
Forum version: 0.1.0-beta.16

![Image of Yaktocat](https://i.imgur.com/Co0GvWQ.jpg)

**Comment by davwheat** [comment]
This would make the widget invisible once you have a lot of discussions because of how Flarum auto-loads discussions as you scroll.
